# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-added-large-files
        -   id: detect-aws-credentials
        -   id: debug-statements
    -   repo: https://github.com/Lucas-C/pre-commit-hooks
        rev: v1.1.10
        hooks:
        -   id: forbid-crlf
        -   id: remove-crlf
        -   id: forbid-tabs
        -   id: remove-tabs
    -   repo: https://github.com/psf/black
        rev: 21.9b0
        hooks:
        -   id: black
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.9.1
        hooks:
        -   id: flake8
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.8.0
        hooks:
        -   id: isort
            args: [--profile=black]
    -   repo: https://github.com/tomcatling/black-nb
        rev: 0.5.0
        hooks:
        -   id: black-nb
